module.exports = {
    environment:"dev",
    mysqlConfig:{
        host:'127.0.0.1',       
        user:'root',              
        password:'200118jin',       
        port:'3306',                   
        database:'econnection' 
    },
    security:{
        expiresIn:60*60*24*30,
        sercetKey:'abcdefg'
    },
    wx:{
        appId:"wxa7fa08fdd5c1460c",
        appSercet:"878e7561777f8df1f2e8492491323d3d",
        url:"https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code",
        access_token:"https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s",
        msgSend:"https://api.weixin.qq.com/cgi-bin/message/wxopen/template/send?access_token=%s"
    },
    redisConfig:{
        port:"6379",
        host:"127.0.0.1"
    }
}